services:
  # Service 1: Postgres
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service 2: Redis Job Queue
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Service 3: Nuxt.js Web App & API
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules # Prevents local modules from overwriting containers
      - /app/.nuxt # Prevents local .nuxt build from overwriting containers
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgres
      - redis

  # Service 4: Go Worker
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./worker:/app # Mounts the local Go codebase into the containers
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
