services:
  # Service 1: Redis Job Queue
  redis:
    image: redis:8.0-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Service 2: Nuxt.js Web App & API
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules # Prevents local modules from overwriting containers
      - /app/.nuxt # Prevents local .nuxt build from overwriting containers
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}

      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
    depends_on:
      - redis

  # Service 3: Go Worker
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./worker:/app # Mounts the local Go codebase into the containers
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      - redis

volumes:
  redis_data:
