name: CI -- Worker

on:
  push:
    branches:
      - main
    paths:
      - worker/**
      - .github/workflows/ci-worker.yml
  pull_request:
    branches:
      - main
    paths:
      - worker/**
      - .github/workflows/ci-worker.yml

jobs:
  validate-and-build-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          working-directory: ./worker

      - name: Check formatting and linting with golangci-lint
        run: golangci-lint run
        working-directory: ./worker

      - name: Vet code for errors
        run: go vet
        working-directory: ./worker

      # - name: Run tests
      #   run: go test
      #   working-directory: ./worker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image for worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: false
          load: true
